myRouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
    VpcId:
      Ref: myVPC
    Tags:
    - Key: name
      Value: csye6225-RouteTable

myRoute: 
  Type: AWS::EC2::Route
  Properties:
    RouteTableId:
      Ref: myRouteTable
    DestinationCidrBlock: 0.0.0.0/0
    GatewayId:
      Ref: myInternetGateway


mySubnetRouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    SubnetId:
      Ref: mySubnet1, mySubnet2, mySubnet3  ## 
    RouteTableId:
      Ref: myRouteTable