Description: csye6225 Infrastructure as Code
Parameters:
  VpcCidrBlock:
    Description: "CIDR block for VPC"
    Type: String
    Default: "10.0.0.0/16"
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: 'default'
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  mySubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: "us-east-1a"
      Tags:
      - Keys: Name
        Value: csye6225-subnet1

  # mySubnet2:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId:
  #       Ref: myVPC
  #     CidrBlock: "10.0.2.0/24"
  #     AvailabilityZone: "us-east-1b"
  #     Tags:
  #     - Keys: Name
  #       Value: csye6225-subnet2


  # mySubnet3:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId:
  #       Ref: myVPC
  #     CidrBlock: "10.0.3.0/24"
  #     AvailabilityZone: "us-east-1c"
  #     Tags:
  #     - Keys: Name
  #       Value: csye6225-subnet3
  
  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC
      # DependsOn:
      #   mySubnet1
      Tags:
      - Key: Name
        Value: csye6225-RouteTable

  myRoute: 
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: myRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: myInternetGateway


  mySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: mySubnet1  ##  mySubnet2, mySubnet3
      RouteTableId:
        Ref: myRouteTable

  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Keys: Name
        Value: csye6225-ig-spring2022